cat shCore.js >> all.min.js
cat shAutoloader.js >> all.min.js
cat shBrushAppleScript.js >> all.min.js
cat shBrushAS3.js >> all.min.js
cat shBrushBash.js >> all.min.js
cat shBrushColdFusion.js >> all.min.js
cat shBrushCpp.js >> all.min.js
cat shBrushCSharp.js >> all.min.js
cat shBrushCss.js >> all.min.js
cat shBrushDelphi.js >> all.min.js
cat shBrushDiff.js >> all.min.js
cat shBrushErlang.js >> all.min.js
cat shBrushGroovy.js >> all.min.js
cat shBrushJavaFX.js >> all.min.js
cat shBrushJava.js >> all.min.js
cat shBrushJScript.js >> all.min.js
cat shBrushPerl.js >> all.min.js
cat shBrushPhp.js >> all.min.js
cat shBrushPlain.js >> all.min.js
cat shBrushPowerShell.js >> all.min.js
cat shBrushPython.js >> all.min.js
cat shBrushRuby.js >> all.min.js
cat shBrushSass.js >> all.min.js
cat shBrushScala.js >> all.min.js
cat shBrushSql.js >> all.min.js
cat shBrushVb.js >> all.min.js
cat shBrushXml.js >> all.min.js
